version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=file:./dev.db
      - COOKIE_SECRET=your-secret-here-change-in-production
    privileged: true
    volumes:
      - ./data:/app/prisma